name=RNBOCTRL
version=1.0.0
author=Alexander Ottl
maintainer=Alexander Ottl
sentence=A library for using the teensy 4.1 as an osc controller to a RNBO patch on a Raspyberry Pi
category=Signal Input/Output
depends=ArduinoJSON, QNEthernet, OSCMessage, Wire, U8g2lib